REPLACE INTO `Ingrediente` VALUES (1, 100, 'Kcal', 'Arroz');
REPLACE INTO `Ingrediente` VALUES (2, 101, 'Kcal', 'Feijão');
REPLACE INTO `Ingrediente` VALUES (3, 102, 'Kcal', 'Biscoito');
REPLACE INTO `Ingrediente` VALUES (4, 103, 'Kcal', 'macarrão');
REPLACE INTO `Ingrediente` VALUES (5, 104, 'Kcal', 'Abacate');
REPLACE INTO `Ingrediente` VALUES (6, 105, 'Kcal', 'Abiu');
REPLACE INTO `Ingrediente` VALUES (7, 106, 'Kcal', 'Abiu');
REPLACE INTO `Ingrediente` VALUES (8, 107, 'Kcal', 'Abóbora');
REPLACE INTO `Ingrediente` VALUES (9, 108, 'Kcal', 'Abricó');
REPLACE INTO `Ingrediente` VALUES (10, 109, 'Kcal', 'Abutua');
REPLACE INTO `Ingrediente` VALUES (11, 110, 'Kcal', 'Açaí');
REPLACE INTO `Ingrediente` VALUES (12, 111, 'Kcal', 'Acarajé');
REPLACE INTO `Ingrediente` VALUES (13, 112, 'Kcal', 'Acelga');
REPLACE INTO `Ingrediente` VALUES (14, 113, 'Kcal', 'Acerola');
REPLACE INTO `Ingrediente` VALUES (15, 114, 'Kcal', 'Acumã');
REPLACE INTO `Ingrediente` VALUES (16, 115, 'Kcal', 'Acuri');
REPLACE INTO `Ingrediente` VALUES (17, 116, 'Kcal', 'Aipim');
REPLACE INTO `Ingrediente` VALUES (18, 117, 'Kcal', 'Alcachofra');
REPLACE INTO `Ingrediente` VALUES (19, 118, 'Kcal', 'Aletria');
REPLACE INTO `Ingrediente` VALUES (20, 119, 'Kcal', 'Alface');
REPLACE INTO `Ingrediente` VALUES (21, 120, 'Kcal', 'Alfajor');
REPLACE INTO `Ingrediente` VALUES (22, 121, 'Kcal', 'Alfarroba');
REPLACE INTO `Ingrediente` VALUES (23, 122, 'Kcal', 'Algodão');
REPLACE INTO `Ingrediente` VALUES (24, 123, 'Kcal', 'Almeirão');
REPLACE INTO `Ingrediente` VALUES (25, 124, 'Kcal', 'Almôndega');
REPLACE INTO `Ingrediente` VALUES (26, 125, 'Kcal', 'Ambrosia');
REPLACE INTO `Ingrediente` VALUES (27, 126, 'Kcal', 'Ameixa');
REPLACE INTO `Ingrediente` VALUES (28, 127, 'Kcal', 'Amêndoa');
REPLACE INTO `Ingrediente` VALUES (29, 128, 'Kcal', 'Amendoim');
REPLACE INTO `Ingrediente` VALUES (30, 129, 'Kcal', 'Amora');
REPLACE INTO `Ingrediente` VALUES (31, 130, 'Kcal', 'Anajá');
REPLACE INTO `Ingrediente` VALUES (32, 131, 'Kcal', 'Ananás');
REPLACE INTO `Ingrediente` VALUES (33, 132, 'Kcal', 'Angá');
REPLACE INTO `Ingrediente` VALUES (34, 133, 'Kcal', 'Angu');
REPLACE INTO `Ingrediente` VALUES (35, 134, 'Kcal', 'Antepasto');
REPLACE INTO `Ingrediente` VALUES (36, 135, 'Kcal', 'Araçá');
REPLACE INTO `Ingrediente` VALUES (37, 136, 'Kcal', 'Araçá');
REPLACE INTO `Ingrediente` VALUES (38, 137, 'Kcal', 'Araticum');
REPLACE INTO `Ingrediente` VALUES (39, 138, 'Kcal', 'Aroeira');
REPLACE INTO `Ingrediente` VALUES (40, 139, 'Kcal', 'Arroz');
REPLACE INTO `Ingrediente` VALUES (41, 140, 'Kcal', 'Arroz');
REPLACE INTO `Ingrediente` VALUES (42, 141, 'Kcal', 'Arroz');
REPLACE INTO `Ingrediente` VALUES (43, 142, 'Kcal', 'Arroz');
REPLACE INTO `Ingrediente` VALUES (44, 143, 'Kcal', 'Asa');
REPLACE INTO `Ingrediente` VALUES (45, 144, 'Kcal', 'Aspargo');


REPLACE INTO `Categoria` VALUES (1,'Bolos e tortas doces');
REPLACE INTO `Categoria` VALUES (2,'Carnes');
REPLACE INTO `Categoria` VALUES (3,'Aves');
REPLACE INTO `Categoria` VALUES (4,'Peixes e frutos do mar');
REPLACE INTO `Categoria` VALUES (5,'Saladas, molhos e acompanhamentos');
REPLACE INTO `Categoria` VALUES (6,'Sopas');
REPLACE INTO `Categoria` VALUES (7,'Massas');
REPLACE INTO `Categoria` VALUES (8,'Bebidas');
REPLACE INTO `Categoria` VALUES (9,'Doces e sobremesas');
REPLACE INTO `Categoria` VALUES (10,'Lanches');
REPLACE INTO `Categoria` VALUES (11,'Prato Único');
REPLACE INTO `Categoria` VALUES (12,'Light');
REPLACE INTO `Categoria` VALUES (13,'Alimentação Saudável');

